with base as (
    select
        customer_id,
        account_officer_id,
        sector_code,
        industry_code,
        target_code,
        customer_since_date,
        title,
        gender,
        marital_status,
        number_of_dependents,
        employment_status,
        job_title,
        monthly_salary,
        nationality_code,
        residence_country_code,
        residence_status,
        segment_code,
        client_nature_code,
        legal_capacity_flag,
        beneficial_owner_flag
    from {{ ref('int_customer_enriched') }}
)
select
    customer_id,
    account_officer_id,
    sector_code,
    industry_code,
    target_code,
    customer_since_date,
    title,
    gender,
    marital_status,
    number_of_dependents,
    employment_status,
    job_title,
    monthly_salary,
    nationality_code,
    residence_country_code,
    residence_status,
    segment_code,
    client_nature_code,
    legal_capacity_flag,
    beneficial_owner_flag
from base

union all

select
    cast(-1 as bigint) as customer_id,
    cast(null as int) as account_officer_id,
    cast(null as int) as sector_code,
    cast(null as int) as industry_code,
    cast(null as int) as target_code,
    cast(null as date) as customer_since_date,
    'UNKNOWN' as title,
    'UNKNOWN' as gender,
    'UNKNOWN' as marital_status,
    cast(null as int) as number_of_dependents,
    'UNKNOWN' as employment_status,
    'UNKNOWN' as job_title,
    cast(null as decimal(18, 2)) as monthly_salary,
    'UNKNOWN' as nationality_code,
    'UNKNOWN' as residence_country_code,
    'UNKNOWN' as residence_status,
    cast(null as int) as segment_code,
    'UNKNOWN' as client_nature_code,
    'UNKNOWN' as legal_capacity_flag,
    'UNKNOWN' as beneficial_owner_flag
