with customer_base as (
    select *
    from {{ ref('int_customer_enriched') }}
)
select
    row_number() over (order by customer_id) as customer_sk,
    customer_id,
    account_officer_id,
    dao_name,
    dao_area,
    parent_department_code,
    sector_code,
    sector_description,
    industry_code,
    industry_description,
    target_code,
    target_description,
    industry_code_raw,
    target_code_raw,
    is_industry_code_remapped,
    is_target_code_remapped,
    customer_since_date,
    customer_tenure_days,
    title,
    gender,
    marital_status,
    number_of_dependents,
    employment_status,
    job_title,
    monthly_salary,
    nationality_code,
    residence_country_code,
    residence_status,
    last_kyc_review_date,
    next_kyc_review_date,
    is_kyc_complete,
    is_pep,
    is_compliance_flagged,
    has_compliance_decision,
    posting_restriction_code,
    segment_code,
    client_nature_code,
    legal_capacity_flag,
    beneficial_owner_flag,
    publication_date,
    turnover_amount,
    turnover_year,
    kyc_score,
    source_record_id,
    extracted_at_utc
from customer_base
