with customer_base as (
    select *
    from {{ ref('int_customer_enriched') }}
    where customer_id is not null  -- never allow NULL PKs into the dimension
      and customer_id <> -1         -- reserve -1 for the single UNKNOWN row
),
all_customers as (
    select *
    from customer_base
    
    union all
    
    -- UNKNOWN sentinel row: used when fact table cannot resolve a customer
    select
        cast(-1 as bigint) as customer_id,
        cast(-1 as int) as sector_code,
        'UNKNOWN' as sector_description,
        cast(-1 as int) as industry_code,
        'UNKNOWN' as industry_description,
        cast(-1 as int) as target_code,
        'UNKNOWN' as target_description,
        cast(-1 as int) as industry_code_raw,
        cast(-1 as int) as target_code_raw,
        cast(0 as bit) as is_industry_code_remapped,
        cast(0 as bit) as is_target_code_remapped,
        cast(-1 as int) as account_officer_id,
        'UNKNOWN' as dao_name,
        'UNKNOWN' as dao_area,
        cast(-1 as int) as parent_department_code,
        cast('1900-01-01' as date) as customer_since_date,
        0 as customer_tenure_days,
        'UNKNOWN' as title,
        'UNKNOWN' as gender,
        'UNKNOWN' as marital_status,
        0 as number_of_dependents,
        'UNKNOWN' as employment_status,
        'UNKNOWN' as job_title,
        cast(0.00 as decimal(18, 2)) as monthly_salary,
        'UNKNOWN' as nationality_code,
        'UNKNOWN' as residence_country_code,
        'UNKNOWN' as residence_status,
        cast('1900-01-01' as date) as last_kyc_review_date,
        cast('1900-01-01' as date) as next_kyc_review_date,
        cast(0 as bit) as is_kyc_complete,
        cast(0 as bit) as is_pep,
        cast(0 as bit) as is_compliance_flagged,
        cast(0 as bit) as has_compliance_decision,
        'UNKNOWN' as posting_restriction_code,
        cast(-1 as int) as segment_code,
        'UNKNOWN' as client_nature_code,
        'UNKNOWN' as legal_capacity_flag,
        'UNKNOWN' as beneficial_owner_flag,
        cast('1900-01-01' as date) as publication_date,
        cast(0.00 as decimal(18, 2)) as turnover_amount,
        1900 as turnover_year,
        'UNKNOWN' as kyc_score,
        'UNKNOWN' as source_record_id,
        cast('1900-01-01' as datetime) as extracted_at_utc
)
select
    row_number() over (order by customer_id) as customer_sk,
    coalesce(customer_id, -1) as customer_id,
    coalesce(account_officer_id, -1) as account_officer_id,
    coalesce(dao_name, 'UNKNOWN') as dao_name,
    coalesce(dao_area, 'UNKNOWN') as dao_area,
    coalesce(parent_department_code, -1) as parent_department_code,
    coalesce(sector_code, -1) as sector_code,
    coalesce(sector_description, 'UNKNOWN') as sector_description,
    coalesce(industry_code, -1) as industry_code,
    coalesce(industry_description, 'UNKNOWN') as industry_description,
    coalesce(target_code, -1) as target_code,
    coalesce(target_description, 'UNKNOWN') as target_description,
    coalesce(industry_code_raw, -1) as industry_code_raw,
    coalesce(target_code_raw, -1) as target_code_raw,
    coalesce(is_industry_code_remapped, cast(0 as bit)) as is_industry_code_remapped,
    coalesce(is_target_code_remapped, cast(0 as bit)) as is_target_code_remapped,
    coalesce(customer_since_date, cast('1900-01-01' as date)) as customer_since_date,
    coalesce(customer_tenure_days, 0) as customer_tenure_days,
    coalesce(title, 'UNKNOWN') as title,
    coalesce(gender, 'UNKNOWN') as gender,
    coalesce(marital_status, 'UNKNOWN') as marital_status,
    coalesce(number_of_dependents, 0) as number_of_dependents,
    coalesce(employment_status, 'UNKNOWN') as employment_status,
    coalesce(job_title, 'UNKNOWN') as job_title,
    coalesce(monthly_salary, cast(0.00 as decimal(18, 2))) as monthly_salary,
    coalesce(nationality_code, 'UNKNOWN') as nationality_code,
    coalesce(residence_country_code, 'UNKNOWN') as residence_country_code,
    coalesce(residence_status, 'UNKNOWN') as residence_status,
    coalesce(last_kyc_review_date, cast('1900-01-01' as date)) as last_kyc_review_date,
    coalesce(next_kyc_review_date, cast('1900-01-01' as date)) as next_kyc_review_date,
    coalesce(is_kyc_complete, cast(0 as bit)) as is_kyc_complete,
    coalesce(is_pep, cast(0 as bit)) as is_pep,
    coalesce(is_compliance_flagged, cast(0 as bit)) as is_compliance_flagged,
    coalesce(has_compliance_decision, cast(0 as bit)) as has_compliance_decision,
    coalesce(posting_restriction_code, 'UNKNOWN') as posting_restriction_code,
    coalesce(segment_code, -1) as segment_code,
    coalesce(client_nature_code, 'UNKNOWN') as client_nature_code,
    coalesce(legal_capacity_flag, 'UNKNOWN') as legal_capacity_flag,
    coalesce(beneficial_owner_flag, 'UNKNOWN') as beneficial_owner_flag,
    coalesce(publication_date, cast('1900-01-01' as date)) as publication_date,
    coalesce(turnover_amount, cast(0.00 as decimal(18, 2))) as turnover_amount,
    coalesce(turnover_year, 1900) as turnover_year,
    coalesce(kyc_score, 'UNKNOWN') as kyc_score,
    coalesce(source_record_id, 'UNKNOWN') as source_record_id,
    coalesce(extracted_at_utc, cast('1900-01-01' as datetime)) as extracted_at_utc
from all_customers
